Repository stolostron/cluster-image-set-controller, pull requests merged in 2025-09, with the labels that each got.

#299 fix konfluxRef pipelineRun lint error
  .tekton/cluster-image-set-controller-mce-28-push.yaml
Labels: approved, dco-signoff: yes

#300 move to konflux common pipeline
  .tekton/cluster-image-set-controller-mce-29-pull-request.yaml
  .tekton/cluster-image-set-controller-mce-29-push.yaml
Labels: approved, dco-signoff: yes

#302 update imagesets for MCE 2.10
  pkg/controller/gitrepo.go
Labels: lgtm, approved, dco-signoff: yes

#305 Add repository url label to container images
  Dockerfile.rhtap
Labels: lgtm, approved, dco-signoff: yes

#304 Add CLAUDE.md documentation
  CLAUDE.md
Labels: ok-to-test, dco-signoff: no
